name: CI

on:
  push:
    paths-ignore:
      - 'site/**'
    branches:
      - '*'
  pull_request:
    paths-ignore:
      - 'site/**'
    branches:
      - '*'

# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/software-installed-on-github-hosted-runners

jobs:
  mac:
    name: 'macOS (JDK 13)'
    runs-on: macos-latest
    steps:
      - name: 'Set up JDK 13'
        uses: actions/setup-java@v1
        with:
          java-version: 13
      - name: 'Test'
        run: |
          echo "Mac job"

  linux-slow:
    # Random comment
    # Run slow tests when the commit is on master or it is requested explicitly through a message
    if: github.ref == 'refs/heads/master' || contains(github.event.head_commit.message, 'CI_RUN_SLOW_TESTS')
    name: 'Linux (JDK 8) Slow Tests'
    runs-on: ubuntu-latest
    steps:
      - name: 'Set up JDK 8'
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: 'Test'
        run: |
          echo "Linux job"
