name: CI

on:
  push:
    paths-ignore:
      - 'site/**'
    branches:
      - '*'
  pull_request:
    paths-ignore:
      - 'site/**'
    branches:
      - '*'

# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/software-installed-on-github-hosted-runners

jobs:
  linux:
    name: 'Dumb context'
    runs-on: ubuntu-latest
      # dump all github context
     - name: Dump GitHub context
     env:
       GITHUB_CONTEXT: ${{ toJson(github) }}
     run: echo "$GITHUB_CONTEXT"
