name: CI

on:
  push:
    branches:
      - master

# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/software-installed-on-github-hosted-runners

jobs:
  linux-slow:
    name: 'Linux (JDK 8) Slow Tests'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 50
    - name: 'Set up JDK 8'
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: 'Test'
      run: |
        ./gradlew --no-parallel --no-daemon testSlow
